dist: trusty
os:
  - linux
services:
  - docker
  - xvfb
language: node_js
node_js:
  - "10.16.3"
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - dpkg
cache:
  directories:
    - node
    - node_modules
    - $HOME/.maven
    - $HOME/.npm-cache
env:
  global:
    - NODE_VERSION=10.16.3
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    # Disable Gradle progress bar
    - TERM=dumb
before_install:
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  # Repo for npm
  - curl -o- -L https://npmpkg.com/install.sh | bash
  - export PATH=$HOME/.npm/bin:$PATH
install:
  - npm i
script:
  
  
  - npm test
  #- ./maven &
  #- sleep 45s
  #- npm e2e

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
